### PR TITLE
Added optional weights to sorted set operation

### PR DESCRIPTION
**Pull request by almost**

### CODE REVIEW

**Comment by j4mie** [comment]
Thanks Tom! This looks great. I'm a bit confused by why I can see loads of my commits in the pull request, and why it can't be automatically merged.. possibly something odd happened at the point where I refactored everything into a package.

I'll try to figure it out and merge when I get a chance..

**Comment by almost** [comment]
Yeah, i'm not sure why they're their either. I think I messed up somewhere. I could get rid of all my commits and do a new pull request for the difference if that would help.

**Comment by j4mie** [comment]
If that's easy, sure. Otherwise, I can just pull down your branch and cherry-pick your commits onto master..

**Comment by j4mie** [comment]
Hi Tom,

Really sorry for the delay on getting this in!

I've finally merged it by cherry-picking your commits into my branch. Not quite sure how git/github got itself confused. I had to make a few changes to your tests to ensure they work on Python 2.6 (the `with self.assertRaises` context manager was only added in 2.7).

The build is currently failing, but I'm 99% sure that's due to a problem with travis-ci. I'll hold off until it's sorted out and then release 0.12.0

Cheers!

**Comment by almost** [comment]
Thanks Jamie! I'm sure it was much more me confusing git than git getting itself confused :)

**Comment by j4mie** [comment]
Finally (!) got around to releasing 0.12.0.

Thanks again! http://pypi.python.org/pypi/rediset/0.12.0

**Comment by almost** [comment]
Awesome! I'll switch over my requirements.txt :)

**Pull request closed without merging**
